baseURL = "https://suspicious-austin-63e510.netlify.com/"
languageCode = "pt-br"
title = "Alpha Church"
theme = "alpha-church"

rssLimit = 5

enableEmoji = true

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[taxonomies]
  tag = "tags"
  preacher = "preachers"
  series = "series"

#This theme can generate a multi-level menu.
#Use weight= to specify the order of menu items, and parent= to create a submenu item.
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 2

  [[menu.main]]
    name = "About Us"
    parent = "About"
    url = "/about"
    weight = 1

  [[menu.main]]
    name = "Leaders"
    parent = "About"
    url = "/leaders"
    weight = 2

  [[menu.main]]
    name = "Resources"
    url = "#"
    weight = 3

  [[menu.main]]
    name = "Sermons"
    url = "/sermons"
    parent = "Resources"
    weight = 1

  [[menu.main]]
    name = "Blog"
    url = "/posts"
    parent = "Resources"
    weight = 2

  [[menu.main]]
    name = "Contact"
    url = "/contact"
    weight = 4

# Paramaters for the whole site
[params]
  title = "Villa da Graça"
  
  author = "Gabriel da Cunha"

  customCSS = ["example.css"]

  bible_popups = "faithlife" #faithlife, blb
  bible_version = "CSB" #HCSB, NIV, NLT, ESV, etc.
  instant_page = true

  [params.podcast]
    title = "Listen to Alpha Church"
    subtitle = ""
    summary = "Alpha-Church sermons, talks, messages—podcasted."
    email = "test@example.com"
    copyright = "Podcast: [CC0 (public domain)](//creativecommons.org/publicdomain/zero/1.0/)"
    image = "img/podcast-cover.jpg"
    category = "Religion & Spirituality"
    sub_category = "Christianity"
    iTunes = "https://itunes.apple.com/us/podcast/tgc-word-of-the-week/id1034013280"
    feed = "https://www.thegospelcoalition.org/podcasts/word-of-the-week/feed/?feed=podcast"

  [params.map]
    service = "google"
    latitude = "-26.281366"
    longitude = "-48.836178"
    zoom = "18"
    api_key = "AIzaSyAtYGL50e7uFCOlIfivqO4SItHt5S3KsPU"

  [params.contact]
    #Use this section to automate contact form.
    #Set service to either "netlify" or "formspree"
    #For formspree, please setup an account at https://formspree.io/
    #For netlify, please read https://www.netlify.com/docs/form-handling/
    #
    #If you use netlify, you'll need to set the confirm_page value (or elase users will see a generic netlify response)
    #If you use formspree, you'll need to set your formspree email address.
    service = "netlify"
    confirm_page = "/contact_thanks"
    # formspree_email=""

  #Paramaters for the home/landing page
  [params.landing]

    [params.landing.banner]
      image = "img/banner.jpg"

    #Details for the box below the banner
    [params.landing.services]
      title = "Culto aos Domingos"
      text = "Nosso culto público acontece todo domingo, às 19h, na [Rua Carlos Benack, 553 - Saguaçu, Joinville](https://goo.gl/maps/7qhtZ4MG3wm)."
      service = "google"
      latitude = "-26.281611"
      longitude = "-48.836243"
      zoom = "5"
      api_key = "AIzaSyCM6YjfE1a_m2ix1XsynzBbJ7kOhwF5Q6g"

    [params.landing.feature_icons]
      #These feature icons look best if there's an even number of them.
      enable = true

      [[params.landing.feature_icons.tile]]
        icon = "fa-praying-hands"
        icon_pack = "fas"
        accent = "5"
        title = "Oração"
        text = "Toda terça, às 20h, nos reunimos para orar uns pelos outros."

      #Accent is a colour defined in the CSS file. Choose between 1 and 5
      [[params.landing.feature_icons.tile]]
        icon = "fa-bible"
        icon_pack = "fas"
        accent = "1"
        title = "Escola bíblica dominical"
        text = "Todo domingo, às 9h, temos aula de teologia."

      [[params.landing.feature_icons.tile]]
        icon = "fa-church"
        icon_pack = "fas"
        accent = "2"
        title = "Uma igreja confessional"
        text = "Afirmamos tudo o que consta na [Confissão de fé de Westminster](http://www.monergismo.com/textos/credos/cfw.htm)"

      [[params.landing.feature_icons.tile]]
        icon = "fa-heartbeat"
        icon_pack = "fas"
        accent = "3"
        title = "Loved"
        text = "Knowing Love. Being Loved."

    [params.landing.feature_images]
      #These feature images look best if there's an even number of them.
      enable = true

      [[params.landing.feature_images.tile]]
        image = "img/freely-10057.jpg"
        title = "Childrens' Ministry"
        text = "A church for the family."
        url = "/kids"
        button_text = "Learn more"

      [[params.landing.feature_images.tile]]
        image = "img/freely-26905.jpg"
        title = "Midweek Ministries"
        text = "Want more during the week?"
        url = "#"
        button_text="Join a group today!"

    [params.landing.CTA]
      heading = "Get in touch!"
      message = "We'd love to hear from you."

    [params.footer]
      copyright = ["[CC0 (public domain)](//creativecommons.org/publicdomain/zero/1.0/)",
                   "Design: [HTML5 UP](//html5up.net/alpha)",
                   "[Hugo Port](//gohugo.io) by [Daniel Saunders](//github.com/funkydan2)"
                  ]

    [[params.links]]
      service = "Twitter"
      icon = "fa-twitter"
      icon_pack = "fab"
      link = "//twitter.com/"

    [[params.links]]
      service = "Facebook"
      icon = "fa-facebook"
      icon_pack = "fab"
      link = "//facebook.com/"

    [[params.links]]
      service = "Podcast"
      icon = "fa-podcast"
      icon_pack = "fas"
      link = "/sermons/index.xml"

    [[params.links]]
      service = "Full RSS Feed"
      icon = "fa-rss"
      icon_pack = "fas"
      link = "/index.xml"
